# Generated by Django 5.0.6 on 2024-09-10 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_account_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('CURRENT', 'Current')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cheque_book_issued', models.BooleanField(default=False)),
                ('cheque_leaves_remaining', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(choices=[('KES', 'KES'), ('USD', 'USD'), ('EUR', 'Euro'), ('GBP', 'GBP')], default='KES', max_length=3)),
                ('bank', models.CharField(choices=[('KCB', 'Kenya Commercial Bank'), ('NCBA', 'NCBA Bank'), ('EQUITY', 'Equity Bank'), ('ABSA', 'ABSA Bank'), ('COOP', 'Co-operative Bank'), ('I&M', 'I&M Bank'), ('SIDIAN', 'SIDIAN Bank'), ('FAMILY', 'FAMILY Bank'), ('HFC', 'HFC Bank'), ('STANCHART', 'STANCHART Bank')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('mpesa_number', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('PERSONAL', 'Personal Phone Number'), ('TILL', 'Mpesa Till')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account_number',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccount'),
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(max_length=20, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced'), ('CANCELLED', 'Cancelled'), ('STALE', 'Stale')], default='PENDING', max_length=10)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='banking.bankaccount')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='mpesa_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.mpesaaccount'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('EFT', 'Electronic Funds Transfer'), ('RTGS', 'Real Time Gross Settlement')], max_length=4)),
                ('transfer_destination', models.CharField(choices=[('INTRABANK', 'Within Same Bank'), ('INTERBANK', 'To Other Bank')], max_length=11)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('recipient_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='banking.bankaccount')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='banking.bankaccount')),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
