# Generated by Django 5.0.6 on 2024-09-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_bankaccount_mpesaaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='cheque_leaves_remaining',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
