# Generated by Django 5.0.6 on 2024-09-12 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_bankaccount_cheque_leaves_remaining'),
        ('purchases', '0004_purchase_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque', to='purchases.purchase'),
        ),
    ]
