# Generated by Django 5.0.6 on 2024-09-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_purchase_item_remove_purchase_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('CHEQUE', 'Cheque'), ('MPESA', 'Mpesa'), ('CASH', 'Cash')], default='CASH', max_length=20),
        ),
    ]
