# Generated by Django 5.0.6 on 2024-09-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='tax_type',
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='tax_type',
            field=models.CharField(choices=[('16% VAT', '16% VAT'), ('EXEMPT', 'EXEMPT'), ('2% CATERING', '2% CATERING LEVY'), ('14% VAT', '14% VAT')], default='EXEMPT', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('CHEQUE', 'Cheque'), ('MPESA', 'Mpesa'), ('CASH', 'Cash'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20),
        ),
    ]
